In [32]:
import numpy as np
np.__version__

'1.14.3'

In [34]:
np.random.randint(20, 30, size=(2, 3))

array([[26, 21, 22],
       [20, 28, 21]])

In [35]:
np.array([1, 2, 3])

array([1, 2, 3])

### 创建 多维数组

In [36]:
np.array([3, 4, 5, 5])

array([3, 4, 5, 5])

In [37]:
import matplotlib.pyplot as plt

In [38]:
np.array([2.1, 2, 4])

array([2.1, 2. , 4. ])

### 常见的函数 (rountines)

多维数组，数组里面嵌套数组

In [39]:
np.ones(shape=(2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.ones(shape=(2,3), dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [45]:
np.zeros(shape=(5, 5), dtype=np.int8) # 创建数组

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [49]:
np.full(shape=(2,3), fill_value=5, dtype=np.int8)

array([[5, 5, 5],
       [5, 5, 5]], dtype=int8)

In [51]:
np.eye(5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [52]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [55]:
np.logspace(1, 3, 3)

array([  10.,  100., 1000.])

In [57]:
np.arange(2, 10, 1)  # 最后一个值是取不到的

array([2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.random.randint(2, 4, size=(3, 3), dtype=np.int8)

array([[3, 3, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int8)

In [60]:
np.random.randn(1, 9)  # 产生传入几个参数就创建一个几维的数组

array([[-1.11178991,  0.47395717, -0.72946494, -0.56398907,  0.96377469,
         0.26648851, -0.78177721, -1.20676827,  0.71353025]])

In [63]:
np.random.normal(loc=10, scale=3, size=(2, 8))   # 可以自己设定分布的中心和方差 


array([[ 9.42441041, 10.03229346,  7.90604822,  9.42321586,  9.55514417,
         7.51251441, 10.16021215,  8.42214999],
       [ 8.87439143, 10.9416016 , 16.34156302,  7.47812133,  9.26263126,
         6.57544089, 13.22349391, 10.93539839]])

In [64]:
np.random.random(size=(2, 3))

array([[0.92052264, 0.15061615, 0.66110172],
       [0.7384865 , 0.21964783, 0.96091695]])

## 随机产生一张图片


In [90]:
import matplotlib.pyplot as plt


In [68]:
img = plt.imread("../ex/icon.jpg")

In [71]:
plt.imshow(img)
plt.show()

In [85]:
img.ndim
img.shape
img.size  # 多维数组的元素的总的个数
img.dtype   # 内部元素的数据类型

dtype('uint8')

In [91]:
img1 = np.random.randint(0, 255, size=(200, 180, 3))
plt.imshow(img1)
plt.show()