# ndarray 排序

代码越少越好

In [9]:
import numpy as np

n1 = np.array([1, 3, 2, 9, 3, 2])

In [8]:
# 经典的冒泡排序
# 两层for 循环是时间 和 空间复杂度增加

def sortn(nd):
    for i in range(nd.size):
        for j in range(i, nd.size):
            
            if nd[i] > nd[j]:
                nd[i], nd[j] = nd[j], nd[i]
    return nd
            

In [7]:
sortn(n1)

array([1, 2, 2, 3, 3, 9])

#### 降低 运算的时间和空间复杂度， 一层 for循环

In [14]:
# 得到最小值的 索引
def sortnd(nd):
    for i in range(nd.size):
        min_index = np.argmin(nd[i:]) + i
#         print(min_index)
        nd[i], nd[min_index] = nd[min_index], nd[i]
    return nd


In [15]:
sortnd(n1)

array([1, 2, 2, 3, 3, 9])

## 快速排序

np.sort() 和 ndarray.sort() 

- np.sort() 不改变输入  有返回值
- ndarray.sort() 无返回值，本地处理， 不占用空间，但改变输入

In [17]:
n1 = np.array([2, 9, 3, 8, 1, 4])
n1.sort()
n1

array([1, 2, 3, 4, 8, 9])

## 部分排序

np.partition(a, k),  得到最大或最小的数， 但不会排序

- k 为正时，得到最小的 k 个数
- k 为负是，得到需要的最大的 k 个数, 放在末尾

In [25]:
nd = np.random.randint(0, 150, size=20)

In [26]:
nd

array([137, 121,  19, 146,  66,  79,  55,  75,  72, 112, 103,  49,  98,
        20, 106, 121,  61,  89,  76,   4])

In [27]:
np.partition(nd, -5)

array([ 61,   4,  19,  76,  66,  79,  55,  75,  72,  89, 103,  49,  98,
        20, 106, 112, 121, 121, 146, 137])

In [28]:
np.partition(nd, 5)

array([ 19,   4,  20,  55,  49,  61,  66,  72,  75,  89, 103,  79,  98,
        76, 106, 112, 121, 121, 146, 137])